
services:
  nextjs:
    build: .
    container_name: cataloger-app
    environment:
      - NEXTAUTH_URL=http://10.2.42.18:3000
      - JWT_SECRET=FOqDtFjZ&-=#0)Zfs#(@,BuW=nlk&MS[!xXmcAEy3-c
      - NODE_ENV=production
      - NODE_ENV_BACKEND_API=http://fastapi_app:8001
      - NEXT_PUBLIC_BACKEND_API=http://fastapi_app:8001
      - SECURE_COOKIES=false
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynet

networks:
  mynet:
    external: true
